### ISSUE TITLE
Cepstral coefficients

### ISSUE THREAD

**Issue by aalesar** [tomasz-oponowicz/spoken_language_identification#1]
Hi ,
Thanks a lot for your work , 
Can you please explain why you removed cepstral coefficients calculation?

**Comment by tomasz-oponowicz** [comment]
@aalesar hi Michael

I guess you refer to this snippet:
https://github.com/tomasz-oponowicz/spoken_language_identification/blob/master/features.py#L104 

I commented this out because I don't eventually use MFCC (probably the function name should be refactored to avoid confusion).

I did some tests and I found out that suprisngly MFCC features don't improve the performance.

**Comment by aalesar** [comment]
Got it,
Thanks a lot for a quick response!
